[build]
  publish = "build"
  command = "pnpm run build"

# SPA redirects - serve index.html for all routes
# This maintains the URL in the browser while serving index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
